# CUDA_VISIBLE_DEVICES=7 python run_net.py --seq_length 56 --model_type LINEAR
# CUDA_VISIBLE_DEVICES=6 python run_net.py --seq_length 56 --model_type GRU
# CUDA_VISIBLE_DEVICES=5 python run_net.py --seq_length 56 --model_type LSTM
# CUDA_VISIBLE_DEVICES=4 python run_net.py --seq_length 56 --model_type SEQ2SEQ
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 112 --model_type LINEAR
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 112 --model_type GRU
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 112 --model_type LSTM
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 112 --model_type SEQ2SEQ
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 168 --model_type LINEAR
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 168 --model_type GRU
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 168 --model_type LSTM
CUDA_VISIBLE_DEVICES=3 python run_net.py --seq_length 168 --model_type SEQ2SEQ
